import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Modal from "@/components/Modal";

export const metadata: Metadata = {
  title: "DreamCanvas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          {children}
          <Modal />
        </body>
      </html>
    </ClerkProvider>
  );
}
